apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: v1.10.0
appVersion: "v1.10.0"
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.10.0
